// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a fresh 256-bit AEAD file key from the OS CSPRNG. Use
/// once per attachment — never reuse across blobs.
Uint8List generateFileKey() =>
    RustLib.instance.api.crateApiAttachmentsGenerateFileKey();

/// Encrypts `plaintext` under `file_key` with a fresh random nonce.
/// Output layout: `[nonce(12) || ciphertext || tag(16)]`. The nonce
/// is prepended so the recipient can decrypt with just the file key
/// and the blob bytes — no separate nonce transport.
Uint8List encryptAttachment(
        {required List<int> fileKey, required List<int> plaintext}) =>
    RustLib.instance.api.crateApiAttachmentsEncryptAttachment(
        fileKey: fileKey, plaintext: plaintext);

/// Decrypts a blob produced by [encrypt_attachment]. Reads the
/// nonce from the first 12 bytes, decrypts + authenticates the
/// rest. Throws if the blob is too short, the key is wrong, or
/// the tag doesn't verify (tampering / corruption).
Uint8List decryptAttachment(
        {required List<int> fileKey, required List<int> ciphertextWithNonce}) =>
    RustLib.instance.api.crateApiAttachmentsDecryptAttachment(
        fileKey: fileKey, ciphertextWithNonce: ciphertextWithNonce);
