// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a fresh identity keypair backed by the OS CSPRNG
/// (seeded ThreadRng in rand 0.9 — ChaCha12 seeded from OS entropy).
IdentityKeypair generateIdentityKeypair() =>
    RustLib.instance.api.crateApiIdentityGenerateIdentityKeypair();

/// Deserializes an identity keypair and returns just the public-key
/// bytes. Used by tests (round-trip check) and by Dart code that
/// only has the serialized blob in storage and needs to re-derive
/// the public half for upload.
Uint8List identityPublicFromSerialized({required List<int> serialized}) =>
    RustLib.instance.api
        .crateApiIdentityIdentityPublicFromSerialized(serialized: serialized);

/// A version sentinel the Dart smoke test can read to confirm it's
/// actually talking to our Rust lib.
String cryptoVersion() => RustLib.instance.api.crateApiIdentityCryptoVersion();

/// Deterministically derives a libsignal registration id from an
/// identity public key. Same algorithm both sides, so peers compute
/// each other's registration id without it being on the wire —
/// saves a schema change. Identity public keys are already ~random
/// so taking the first 4 bytes is uniformly distributed.
///
/// Accepts both 32-byte raw Curve25519 public keys and 33-byte
/// DJB-prefixed IdentityKey encodings — offsets past the type byte
/// when present so both alice-self-deriving and bob-peer-deriving
/// get the same answer.
int deriveRegistrationId({required List<int> identityPublicKey}) => RustLib
    .instance.api
    .crateApiIdentityDeriveRegistrationId(identityPublicKey: identityPublicKey);

/// An identity keypair.
///
///   `serialized` — libsignal's canonical protobuf encoding of the
///                  full keypair. Opaque to Dart; used for secure
///                  storage and as input to later protocol ops.
///   `public_key` — the 33-byte serialization of the public half
///                  (1-byte DJB type marker + 32-byte Curve25519
///                  public key). This is what goes in the uploaded
///                  key bundle.
class IdentityKeypair {
  final Uint8List serialized;
  final Uint8List publicKey;

  const IdentityKeypair({
    required this.serialized,
    required this.publicKey,
  });

  @override
  int get hashCode => serialized.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityKeypair &&
          runtimeType == other.runtimeType &&
          serialized == other.serialized &&
          publicKey == other.publicKey;
}
