// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import, unintended_html_in_doc_comment

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `now_millis`

/// Generates a fresh X25519 keypair and signs its public half with
/// the IdentityKey loaded from `identity_serialized` (the opaque
/// blob stored at generation time). Returns both the protobuf
/// record (for storage) and the individual upload-ready bytes.
SignedPreKey generateSignedPrekey(
        {required List<int> identitySerialized, required int keyId}) =>
    RustLib.instance.api.crateApiPrekeysGenerateSignedPrekey(
        identitySerialized: identitySerialized, keyId: keyId);

/// Generates `count` One-Time PreKey records with sequential ids
/// starting at `start_id`. Typical first-run call is (1, 100).
///
/// Serialization failures would indicate a logic bug in libsignal
/// (not an input error), so we panic rather than bubble a Result —
/// frb 2.x can't SSE-encode Result<Vec<CustomStruct>> anyway.
List<OneTimePreKey> generatePrekeyBatch(
        {required int startId, required int count}) =>
    RustLib.instance.api
        .crateApiPrekeysGeneratePrekeyBatch(startId: startId, count: count);

/// Generates `count` Kyber prekey records signed by the identity
/// key loaded from `identity_serialized`. IDs are sequential starting
/// at `start_id`. Typical first-run call is `(identity, 1, 20)` —
/// batch is smaller than classical OTPKs because Kyber records are
/// ~3KB each.
List<KyberPreKey> generateKyberPrekeyBatch(
        {required List<int> identitySerialized,
        required int startId,
        required int count}) =>
    RustLib.instance.api.crateApiPrekeysGenerateKyberPrekeyBatch(
        identitySerialized: identitySerialized, startId: startId, count: count);

/// Verifies a Signed PreKey's signature against a given identity
/// public key. Useful for self-check before upload (Dart-side) and
/// for recipients verifying fetched bundles (Phase 1e).
bool verifySignedPrekey(
        {required List<int> identityPublic,
        required List<int> signedPrekeyPublic,
        required List<int> signature}) =>
    RustLib.instance.api.crateApiPrekeysVerifySignedPrekey(
        identityPublic: identityPublic,
        signedPrekeyPublic: signedPrekeyPublic,
        signature: signature);

/// A Kyber (post-quantum) prekey. libsignal hybridized its X3DH to
/// include a PQC leg so a future quantum attacker recording traffic
/// today can't later decrypt it. The key itself is ML-KEM-1024 (aka
/// Kyber1024) — ~1568-byte public half — signed by the IdentityKey's
/// Ed25519 signing capability.
///
/// Consumed one-per-session like a OneTimePreKey. Replenished from
/// the client when the unconsumed pool runs low.
class KyberPreKey {
  final int id;
  final Uint8List serialized;
  final Uint8List publicKey;
  final Uint8List signature;

  const KyberPreKey({
    required this.id,
    required this.serialized,
    required this.publicKey,
    required this.signature,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      serialized.hashCode ^
      publicKey.hashCode ^
      signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KyberPreKey &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serialized == other.serialized &&
          publicKey == other.publicKey &&
          signature == other.signature;
}

class OneTimePreKey {
  final int id;
  final Uint8List serialized;
  final Uint8List publicKey;

  const OneTimePreKey({
    required this.id,
    required this.serialized,
    required this.publicKey,
  });

  @override
  int get hashCode => id.hashCode ^ serialized.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneTimePreKey &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serialized == other.serialized &&
          publicKey == other.publicKey;
}

class SignedPreKey {
  final int id;
  final Uint8List serialized;
  final Uint8List publicKey;
  final Uint8List signature;

  const SignedPreKey({
    required this.id,
    required this.serialized,
    required this.publicKey,
    required this.signature,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      serialized.hashCode ^
      publicKey.hashCode ^
      signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignedPreKey &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serialized == other.serialized &&
          publicKey == other.publicKey &&
          signature == other.signature;
}
