// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `address_for`, `build_store_with`, `load_record`, `parse_distribution_id`

/// Generates (or rotates) our own sender-key chain for this group
/// conversation and returns the SKDM to distribute. Call on:
///   - First group send (no existing record).
///   - Membership change (caller passes `existing_own_record = None`
///     to force a fresh chain, so previously-trusted members lose
///     decrypt ability going forward).
///
/// The caller is responsible for 1:1-encrypting `skdm` to each other
/// current member and delivering it via their existing Double Ratchet
/// session before the first ciphertext encrypted from `updated_record`
/// is broadcast — otherwise recipients receive a group message they
/// cannot decrypt.
GroupSkdmOut createGroupSenderKey(
        {required String ownUserId,
        required String conversationId,
        Uint8List? existingOwnRecord}) =>
    RustLib.instance.api.crateApiSessionGroupCreateGroupSenderKey(
        ownUserId: ownUserId,
        conversationId: conversationId,
        existingOwnRecord: existingOwnRecord);

/// Receiver-side: consume a peer's SKDM and return the updated record
/// to persist. Caller should have already 1:1-decrypted the SKDM from
/// the sender's Double Ratchet envelope before this call.
Uint8List processGroupSenderKey(
        {required String senderUserId,
        required String conversationId,
        required List<int> skdmBytes,
        Uint8List? existingSenderRecord}) =>
    RustLib.instance.api.crateApiSessionGroupProcessGroupSenderKey(
        senderUserId: senderUserId,
        conversationId: conversationId,
        skdmBytes: skdmBytes,
        existingSenderRecord: existingSenderRecord);

/// Sender-side: encrypt `plaintext` for the group. Requires an
/// existing sender-key record (create via [create_group_sender_key]
/// first if we don't have one). Returns the updated record (persist
/// immediately) and the ciphertext (broadcast to the group).
GroupEncryptResult encryptGroup(
        {required String ownUserId,
        required String conversationId,
        required List<int> ownRecord,
        required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSessionGroupEncryptGroup(
        ownUserId: ownUserId,
        conversationId: conversationId,
        ownRecord: ownRecord,
        plaintext: plaintext);

/// Receiver-side: decrypt `ciphertext` sent by `sender_user_id` in
/// this group. Requires the sender's record (populated by a prior
/// [process_group_sender_key] call for this sender + distribution).
GroupDecryptResult decryptGroup(
        {required String senderUserId,
        required String conversationId,
        required List<int> senderRecord,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiSessionGroupDecryptGroup(
        senderUserId: senderUserId,
        conversationId: conversationId,
        senderRecord: senderRecord,
        ciphertext: ciphertext);

/// Dart-facing result of [decrypt_group]. Receiver persists the
/// `updated_record` so later messages in this chain (same sender,
/// same distribution) decrypt without re-processing.
class GroupDecryptResult {
  final Uint8List updatedRecord;
  final Uint8List plaintext;

  const GroupDecryptResult({
    required this.updatedRecord,
    required this.plaintext,
  });

  @override
  int get hashCode => updatedRecord.hashCode ^ plaintext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDecryptResult &&
          runtimeType == other.runtimeType &&
          updatedRecord == other.updatedRecord &&
          plaintext == other.plaintext;
}

/// Dart-facing result of [encrypt_group]. `updated_record` must be
/// persisted before the ciphertext is delivered — the chain advances
/// on every send, so losing the updated state would force every
/// recipient to rebuild their sender-key store.
class GroupEncryptResult {
  final Uint8List updatedRecord;
  final Uint8List ciphertext;

  const GroupEncryptResult({
    required this.updatedRecord,
    required this.ciphertext,
  });

  @override
  int get hashCode => updatedRecord.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupEncryptResult &&
          runtimeType == other.runtimeType &&
          updatedRecord == other.updatedRecord &&
          ciphertext == other.ciphertext;
}

/// Dart-facing result of [create_group_sender_key]. The sender
/// persists `updated_record` keyed by (conversation_id, own_user_id)
/// and fans out `skdm` to each other member, 1:1-encrypted via the
/// existing pairwise Double Ratchet sessions.
class GroupSkdmOut {
  final Uint8List updatedRecord;
  final Uint8List skdm;

  const GroupSkdmOut({
    required this.updatedRecord,
    required this.skdm,
  });

  @override
  int get hashCode => updatedRecord.hashCode ^ skdm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupSkdmOut &&
          runtimeType == other.runtimeType &&
          updatedRecord == other.updatedRecord &&
          skdm == other.skdm;
}
