// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base_stores`, `protocol_address_for`

/// Alice-side session setup: consumes a peer's bundle, produces a
/// SessionRecord. Call this once per peer when you first establish
/// a session (before sending the first message).
///
/// Registration ID is the caller's own id (u32) used by libsignal as
/// a device identifier. Single-device v1 picks a fixed value at
/// identity creation time — we'll derive it from the identity key
/// bytes on the Dart side and pass here.
Uint8List initiate1To1Session(
        {required String ownUserId,
        required String remoteUserId,
        required List<int> ownIdentitySerialized,
        required int ownRegistrationId,
        required int peerRegistrationId,
        required List<int> peerIdentityPub,
        required int peerSignedPrekeyId,
        required List<int> peerSignedPrekeyPub,
        required List<int> peerSignedPrekeySig,
        int? peerOneTimePrekeyId,
        Uint8List? peerOneTimePrekeyPub,
        required int peerKyberPrekeyId,
        required List<int> peerKyberPrekeyPub,
        required List<int> peerKyberPrekeySig}) =>
    RustLib.instance.api.crateApiSession1To1Initiate1To1Session(
        ownUserId: ownUserId,
        remoteUserId: remoteUserId,
        ownIdentitySerialized: ownIdentitySerialized,
        ownRegistrationId: ownRegistrationId,
        peerRegistrationId: peerRegistrationId,
        peerIdentityPub: peerIdentityPub,
        peerSignedPrekeyId: peerSignedPrekeyId,
        peerSignedPrekeyPub: peerSignedPrekeyPub,
        peerSignedPrekeySig: peerSignedPrekeySig,
        peerOneTimePrekeyId: peerOneTimePrekeyId,
        peerOneTimePrekeyPub: peerOneTimePrekeyPub,
        peerKyberPrekeyId: peerKyberPrekeyId,
        peerKyberPrekeyPub: peerKyberPrekeyPub,
        peerKyberPrekeySig: peerKyberPrekeySig);

/// Encrypts `plaintext` against the session stored at `session_
/// serialized`. Returns the new session state (to persist) + the
/// ciphertext bytes (to send) + the message type tag.
EncryptResult encrypt1To1(
        {required String ownUserId,
        required String remoteUserId,
        required List<int> ownIdentitySerialized,
        required int ownRegistrationId,
        required List<int> sessionSerialized,
        required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSession1To1Encrypt1To1(
        ownUserId: ownUserId,
        remoteUserId: remoteUserId,
        ownIdentitySerialized: ownIdentitySerialized,
        ownRegistrationId: ownRegistrationId,
        sessionSerialized: sessionSerialized,
        plaintext: plaintext);

/// Responder-side first-message decrypt. Ciphertext must be a serialized
/// PreKeySignalMessage. Caller supplies the SignedPreKey + OneTimePreKey
/// + KyberPreKey records the message will reference — we don't know
/// which ids it references until libsignal parses it, so Dart passes
/// every unconsumed record (single-device v1 typically keeps the pool
/// small enough that this is fine).
DecryptResult decryptPrekey1To1(
        {required String ownUserId,
        required String remoteUserId,
        required List<int> ownIdentitySerialized,
        required int ownRegistrationId,
        required List<Uint8List> signedPrekeyRecordsSerialized,
        required List<Uint8List> oneTimePrekeyRecordsSerialized,
        required List<Uint8List> kyberPrekeyRecordsSerialized,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiSession1To1DecryptPrekey1To1(
        ownUserId: ownUserId,
        remoteUserId: remoteUserId,
        ownIdentitySerialized: ownIdentitySerialized,
        ownRegistrationId: ownRegistrationId,
        signedPrekeyRecordsSerialized: signedPrekeyRecordsSerialized,
        oneTimePrekeyRecordsSerialized: oneTimePrekeyRecordsSerialized,
        kyberPrekeyRecordsSerialized: kyberPrekeyRecordsSerialized,
        ciphertext: ciphertext);

/// Subsequent-message decrypt on an established session. Ciphertext
/// must be a serialized SignalMessage (not PKM).
DecryptResult decryptSignal1To1(
        {required String ownUserId,
        required String remoteUserId,
        required List<int> ownIdentitySerialized,
        required int ownRegistrationId,
        required List<int> sessionSerialized,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiSession1To1DecryptSignal1To1(
        ownUserId: ownUserId,
        remoteUserId: remoteUserId,
        ownIdentitySerialized: ownIdentitySerialized,
        ownRegistrationId: ownRegistrationId,
        sessionSerialized: sessionSerialized,
        ciphertext: ciphertext);

/// Dart-facing result of decrypt_*.
class DecryptResult {
  /// Updated session, to persist.
  final Uint8List updatedSessionSerialized;

  /// Recovered plaintext bytes.
  final Uint8List plaintext;

  const DecryptResult({
    required this.updatedSessionSerialized,
    required this.plaintext,
  });

  @override
  int get hashCode => updatedSessionSerialized.hashCode ^ plaintext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptResult &&
          runtimeType == other.runtimeType &&
          updatedSessionSerialized == other.updatedSessionSerialized &&
          plaintext == other.plaintext;
}

/// Dart-facing result of encrypt_1to1.
class EncryptResult {
  /// Updated session, to be persisted and used for the next encrypt.
  final Uint8List updatedSessionSerialized;

  /// Serialized CiphertextMessage bytes — this is what goes on the
  /// wire (base64-encoded into the message envelope).
  final Uint8List ciphertext;

  /// CiphertextMessageType tag: 2 for PreKeySignalMessage (first
  /// message in a session), 3 for a regular SignalMessage.
  final int messageType;

  const EncryptResult({
    required this.updatedSessionSerialized,
    required this.ciphertext,
    required this.messageType,
  });

  @override
  int get hashCode =>
      updatedSessionSerialized.hashCode ^
      ciphertext.hashCode ^
      messageType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptResult &&
          runtimeType == other.runtimeType &&
          updatedSessionSerialized == other.updatedSessionSerialized &&
          ciphertext == other.ciphertext &&
          messageType == other.messageType;
}
