// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/attachments.dart';
import 'api/identity.dart';
import 'api/prekeys.dart';
import 'api/session_1to1.dart';
import 'api/session_group.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -141737482;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'aside_crypto',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  GroupSkdmOut crateApiSessionGroupCreateGroupSenderKey(
      {required String ownUserId,
      required String conversationId,
      Uint8List? existingOwnRecord});

  String crateApiIdentityCryptoVersion();

  Uint8List crateApiAttachmentsDecryptAttachment(
      {required List<int> fileKey, required List<int> ciphertextWithNonce});

  GroupDecryptResult crateApiSessionGroupDecryptGroup(
      {required String senderUserId,
      required String conversationId,
      required List<int> senderRecord,
      required List<int> ciphertext});

  DecryptResult crateApiSession1To1DecryptPrekey1To1(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required List<Uint8List> signedPrekeyRecordsSerialized,
      required List<Uint8List> oneTimePrekeyRecordsSerialized,
      required List<Uint8List> kyberPrekeyRecordsSerialized,
      required List<int> ciphertext});

  DecryptResult crateApiSession1To1DecryptSignal1To1(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required List<int> sessionSerialized,
      required List<int> ciphertext});

  int crateApiIdentityDeriveRegistrationId(
      {required List<int> identityPublicKey});

  EncryptResult crateApiSession1To1Encrypt1To1(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required List<int> sessionSerialized,
      required List<int> plaintext});

  Uint8List crateApiAttachmentsEncryptAttachment(
      {required List<int> fileKey, required List<int> plaintext});

  GroupEncryptResult crateApiSessionGroupEncryptGroup(
      {required String ownUserId,
      required String conversationId,
      required List<int> ownRecord,
      required List<int> plaintext});

  Uint8List crateApiAttachmentsGenerateFileKey();

  IdentityKeypair crateApiIdentityGenerateIdentityKeypair();

  List<KyberPreKey> crateApiPrekeysGenerateKyberPrekeyBatch(
      {required List<int> identitySerialized,
      required int startId,
      required int count});

  List<OneTimePreKey> crateApiPrekeysGeneratePrekeyBatch(
      {required int startId, required int count});

  SignedPreKey crateApiPrekeysGenerateSignedPrekey(
      {required List<int> identitySerialized, required int keyId});

  Uint8List crateApiIdentityIdentityPublicFromSerialized(
      {required List<int> serialized});

  Future<void> crateApiInitInitApp();

  Uint8List crateApiSession1To1Initiate1To1Session(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required int peerRegistrationId,
      required List<int> peerIdentityPub,
      required int peerSignedPrekeyId,
      required List<int> peerSignedPrekeyPub,
      required List<int> peerSignedPrekeySig,
      int? peerOneTimePrekeyId,
      Uint8List? peerOneTimePrekeyPub,
      required int peerKyberPrekeyId,
      required List<int> peerKyberPrekeyPub,
      required List<int> peerKyberPrekeySig});

  Uint8List crateApiSessionGroupProcessGroupSenderKey(
      {required String senderUserId,
      required String conversationId,
      required List<int> skdmBytes,
      Uint8List? existingSenderRecord});

  bool crateApiPrekeysVerifySignedPrekey(
      {required List<int> identityPublic,
      required List<int> signedPrekeyPublic,
      required List<int> signature});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  GroupSkdmOut crateApiSessionGroupCreateGroupSenderKey(
      {required String ownUserId,
      required String conversationId,
      Uint8List? existingOwnRecord}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(ownUserId, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_opt_list_prim_u_8_strict(existingOwnRecord, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_group_skdm_out,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionGroupCreateGroupSenderKeyConstMeta,
      argValues: [ownUserId, conversationId, existingOwnRecord],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionGroupCreateGroupSenderKeyConstMeta =>
      const TaskConstMeta(
        debugName: "create_group_sender_key",
        argNames: ["ownUserId", "conversationId", "existingOwnRecord"],
      );

  @override
  String crateApiIdentityCryptoVersion() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIdentityCryptoVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentityCryptoVersionConstMeta =>
      const TaskConstMeta(
        debugName: "crypto_version",
        argNames: [],
      );

  @override
  Uint8List crateApiAttachmentsDecryptAttachment(
      {required List<int> fileKey, required List<int> ciphertextWithNonce}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(fileKey, serializer);
        sse_encode_list_prim_u_8_loose(ciphertextWithNonce, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentsDecryptAttachmentConstMeta,
      argValues: [fileKey, ciphertextWithNonce],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentsDecryptAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_attachment",
        argNames: ["fileKey", "ciphertextWithNonce"],
      );

  @override
  GroupDecryptResult crateApiSessionGroupDecryptGroup(
      {required String senderUserId,
      required String conversationId,
      required List<int> senderRecord,
      required List<int> ciphertext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(senderUserId, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_list_prim_u_8_loose(senderRecord, serializer);
        sse_encode_list_prim_u_8_loose(ciphertext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_group_decrypt_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionGroupDecryptGroupConstMeta,
      argValues: [senderUserId, conversationId, senderRecord, ciphertext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionGroupDecryptGroupConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_group",
        argNames: [
          "senderUserId",
          "conversationId",
          "senderRecord",
          "ciphertext"
        ],
      );

  @override
  DecryptResult crateApiSession1To1DecryptPrekey1To1(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required List<Uint8List> signedPrekeyRecordsSerialized,
      required List<Uint8List> oneTimePrekeyRecordsSerialized,
      required List<Uint8List> kyberPrekeyRecordsSerialized,
      required List<int> ciphertext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(ownUserId, serializer);
        sse_encode_String(remoteUserId, serializer);
        sse_encode_list_prim_u_8_loose(ownIdentitySerialized, serializer);
        sse_encode_u_32(ownRegistrationId, serializer);
        sse_encode_list_list_prim_u_8_strict(
            signedPrekeyRecordsSerialized, serializer);
        sse_encode_list_list_prim_u_8_strict(
            oneTimePrekeyRecordsSerialized, serializer);
        sse_encode_list_list_prim_u_8_strict(
            kyberPrekeyRecordsSerialized, serializer);
        sse_encode_list_prim_u_8_loose(ciphertext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_decrypt_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSession1To1DecryptPrekey1To1ConstMeta,
      argValues: [
        ownUserId,
        remoteUserId,
        ownIdentitySerialized,
        ownRegistrationId,
        signedPrekeyRecordsSerialized,
        oneTimePrekeyRecordsSerialized,
        kyberPrekeyRecordsSerialized,
        ciphertext
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSession1To1DecryptPrekey1To1ConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_prekey_1to1",
        argNames: [
          "ownUserId",
          "remoteUserId",
          "ownIdentitySerialized",
          "ownRegistrationId",
          "signedPrekeyRecordsSerialized",
          "oneTimePrekeyRecordsSerialized",
          "kyberPrekeyRecordsSerialized",
          "ciphertext"
        ],
      );

  @override
  DecryptResult crateApiSession1To1DecryptSignal1To1(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required List<int> sessionSerialized,
      required List<int> ciphertext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(ownUserId, serializer);
        sse_encode_String(remoteUserId, serializer);
        sse_encode_list_prim_u_8_loose(ownIdentitySerialized, serializer);
        sse_encode_u_32(ownRegistrationId, serializer);
        sse_encode_list_prim_u_8_loose(sessionSerialized, serializer);
        sse_encode_list_prim_u_8_loose(ciphertext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_decrypt_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSession1To1DecryptSignal1To1ConstMeta,
      argValues: [
        ownUserId,
        remoteUserId,
        ownIdentitySerialized,
        ownRegistrationId,
        sessionSerialized,
        ciphertext
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSession1To1DecryptSignal1To1ConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_signal_1to1",
        argNames: [
          "ownUserId",
          "remoteUserId",
          "ownIdentitySerialized",
          "ownRegistrationId",
          "sessionSerialized",
          "ciphertext"
        ],
      );

  @override
  int crateApiIdentityDeriveRegistrationId(
      {required List<int> identityPublicKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(identityPublicKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIdentityDeriveRegistrationIdConstMeta,
      argValues: [identityPublicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentityDeriveRegistrationIdConstMeta =>
      const TaskConstMeta(
        debugName: "derive_registration_id",
        argNames: ["identityPublicKey"],
      );

  @override
  EncryptResult crateApiSession1To1Encrypt1To1(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required List<int> sessionSerialized,
      required List<int> plaintext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(ownUserId, serializer);
        sse_encode_String(remoteUserId, serializer);
        sse_encode_list_prim_u_8_loose(ownIdentitySerialized, serializer);
        sse_encode_u_32(ownRegistrationId, serializer);
        sse_encode_list_prim_u_8_loose(sessionSerialized, serializer);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_encrypt_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSession1To1Encrypt1To1ConstMeta,
      argValues: [
        ownUserId,
        remoteUserId,
        ownIdentitySerialized,
        ownRegistrationId,
        sessionSerialized,
        plaintext
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSession1To1Encrypt1To1ConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_1to1",
        argNames: [
          "ownUserId",
          "remoteUserId",
          "ownIdentitySerialized",
          "ownRegistrationId",
          "sessionSerialized",
          "plaintext"
        ],
      );

  @override
  Uint8List crateApiAttachmentsEncryptAttachment(
      {required List<int> fileKey, required List<int> plaintext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(fileKey, serializer);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentsEncryptAttachmentConstMeta,
      argValues: [fileKey, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentsEncryptAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_attachment",
        argNames: ["fileKey", "plaintext"],
      );

  @override
  GroupEncryptResult crateApiSessionGroupEncryptGroup(
      {required String ownUserId,
      required String conversationId,
      required List<int> ownRecord,
      required List<int> plaintext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(ownUserId, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_list_prim_u_8_loose(ownRecord, serializer);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_group_encrypt_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionGroupEncryptGroupConstMeta,
      argValues: [ownUserId, conversationId, ownRecord, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionGroupEncryptGroupConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_group",
        argNames: ["ownUserId", "conversationId", "ownRecord", "plaintext"],
      );

  @override
  Uint8List crateApiAttachmentsGenerateFileKey() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAttachmentsGenerateFileKeyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentsGenerateFileKeyConstMeta =>
      const TaskConstMeta(
        debugName: "generate_file_key",
        argNames: [],
      );

  @override
  IdentityKeypair crateApiIdentityGenerateIdentityKeypair() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_identity_keypair,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIdentityGenerateIdentityKeypairConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentityGenerateIdentityKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_identity_keypair",
        argNames: [],
      );

  @override
  List<KyberPreKey> crateApiPrekeysGenerateKyberPrekeyBatch(
      {required List<int> identitySerialized,
      required int startId,
      required int count}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(identitySerialized, serializer);
        sse_encode_u_32(startId, serializer);
        sse_encode_u_32(count, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_kyber_pre_key,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPrekeysGenerateKyberPrekeyBatchConstMeta,
      argValues: [identitySerialized, startId, count],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPrekeysGenerateKyberPrekeyBatchConstMeta =>
      const TaskConstMeta(
        debugName: "generate_kyber_prekey_batch",
        argNames: ["identitySerialized", "startId", "count"],
      );

  @override
  List<OneTimePreKey> crateApiPrekeysGeneratePrekeyBatch(
      {required int startId, required int count}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(startId, serializer);
        sse_encode_u_32(count, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_one_time_pre_key,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPrekeysGeneratePrekeyBatchConstMeta,
      argValues: [startId, count],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPrekeysGeneratePrekeyBatchConstMeta =>
      const TaskConstMeta(
        debugName: "generate_prekey_batch",
        argNames: ["startId", "count"],
      );

  @override
  SignedPreKey crateApiPrekeysGenerateSignedPrekey(
      {required List<int> identitySerialized, required int keyId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(identitySerialized, serializer);
        sse_encode_u_32(keyId, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_signed_pre_key,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPrekeysGenerateSignedPrekeyConstMeta,
      argValues: [identitySerialized, keyId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPrekeysGenerateSignedPrekeyConstMeta =>
      const TaskConstMeta(
        debugName: "generate_signed_prekey",
        argNames: ["identitySerialized", "keyId"],
      );

  @override
  Uint8List crateApiIdentityIdentityPublicFromSerialized(
      {required List<int> serialized}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(serialized, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiIdentityIdentityPublicFromSerializedConstMeta,
      argValues: [serialized],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentityIdentityPublicFromSerializedConstMeta =>
      const TaskConstMeta(
        debugName: "identity_public_from_serialized",
        argNames: ["serialized"],
      );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Uint8List crateApiSession1To1Initiate1To1Session(
      {required String ownUserId,
      required String remoteUserId,
      required List<int> ownIdentitySerialized,
      required int ownRegistrationId,
      required int peerRegistrationId,
      required List<int> peerIdentityPub,
      required int peerSignedPrekeyId,
      required List<int> peerSignedPrekeyPub,
      required List<int> peerSignedPrekeySig,
      int? peerOneTimePrekeyId,
      Uint8List? peerOneTimePrekeyPub,
      required int peerKyberPrekeyId,
      required List<int> peerKyberPrekeyPub,
      required List<int> peerKyberPrekeySig}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(ownUserId, serializer);
        sse_encode_String(remoteUserId, serializer);
        sse_encode_list_prim_u_8_loose(ownIdentitySerialized, serializer);
        sse_encode_u_32(ownRegistrationId, serializer);
        sse_encode_u_32(peerRegistrationId, serializer);
        sse_encode_list_prim_u_8_loose(peerIdentityPub, serializer);
        sse_encode_u_32(peerSignedPrekeyId, serializer);
        sse_encode_list_prim_u_8_loose(peerSignedPrekeyPub, serializer);
        sse_encode_list_prim_u_8_loose(peerSignedPrekeySig, serializer);
        sse_encode_opt_box_autoadd_u_32(peerOneTimePrekeyId, serializer);
        sse_encode_opt_list_prim_u_8_strict(peerOneTimePrekeyPub, serializer);
        sse_encode_u_32(peerKyberPrekeyId, serializer);
        sse_encode_list_prim_u_8_loose(peerKyberPrekeyPub, serializer);
        sse_encode_list_prim_u_8_loose(peerKyberPrekeySig, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSession1To1Initiate1To1SessionConstMeta,
      argValues: [
        ownUserId,
        remoteUserId,
        ownIdentitySerialized,
        ownRegistrationId,
        peerRegistrationId,
        peerIdentityPub,
        peerSignedPrekeyId,
        peerSignedPrekeyPub,
        peerSignedPrekeySig,
        peerOneTimePrekeyId,
        peerOneTimePrekeyPub,
        peerKyberPrekeyId,
        peerKyberPrekeyPub,
        peerKyberPrekeySig
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSession1To1Initiate1To1SessionConstMeta =>
      const TaskConstMeta(
        debugName: "initiate_1to1_session",
        argNames: [
          "ownUserId",
          "remoteUserId",
          "ownIdentitySerialized",
          "ownRegistrationId",
          "peerRegistrationId",
          "peerIdentityPub",
          "peerSignedPrekeyId",
          "peerSignedPrekeyPub",
          "peerSignedPrekeySig",
          "peerOneTimePrekeyId",
          "peerOneTimePrekeyPub",
          "peerKyberPrekeyId",
          "peerKyberPrekeyPub",
          "peerKyberPrekeySig"
        ],
      );

  @override
  Uint8List crateApiSessionGroupProcessGroupSenderKey(
      {required String senderUserId,
      required String conversationId,
      required List<int> skdmBytes,
      Uint8List? existingSenderRecord}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(senderUserId, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_list_prim_u_8_loose(skdmBytes, serializer);
        sse_encode_opt_list_prim_u_8_strict(existingSenderRecord, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionGroupProcessGroupSenderKeyConstMeta,
      argValues: [
        senderUserId,
        conversationId,
        skdmBytes,
        existingSenderRecord
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionGroupProcessGroupSenderKeyConstMeta =>
      const TaskConstMeta(
        debugName: "process_group_sender_key",
        argNames: [
          "senderUserId",
          "conversationId",
          "skdmBytes",
          "existingSenderRecord"
        ],
      );

  @override
  bool crateApiPrekeysVerifySignedPrekey(
      {required List<int> identityPublic,
      required List<int> signedPrekeyPublic,
      required List<int> signature}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(identityPublic, serializer);
        sse_encode_list_prim_u_8_loose(signedPrekeyPublic, serializer);
        sse_encode_list_prim_u_8_loose(signature, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPrekeysVerifySignedPrekeyConstMeta,
      argValues: [identityPublic, signedPrekeyPublic, signature],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPrekeysVerifySignedPrekeyConstMeta =>
      const TaskConstMeta(
        debugName: "verify_signed_prekey",
        argNames: ["identityPublic", "signedPrekeyPublic", "signature"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DecryptResult dco_decode_decrypt_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DecryptResult(
      updatedSessionSerialized: dco_decode_list_prim_u_8_strict(arr[0]),
      plaintext: dco_decode_list_prim_u_8_strict(arr[1]),
      consumedOneTimePrekeyId: dco_decode_opt_box_autoadd_u_32(arr[2]),
      consumedKyberPrekeyId: dco_decode_opt_box_autoadd_u_32(arr[3]),
    );
  }

  @protected
  EncryptResult dco_decode_encrypt_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EncryptResult(
      updatedSessionSerialized: dco_decode_list_prim_u_8_strict(arr[0]),
      ciphertext: dco_decode_list_prim_u_8_strict(arr[1]),
      messageType: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  GroupDecryptResult dco_decode_group_decrypt_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GroupDecryptResult(
      updatedRecord: dco_decode_list_prim_u_8_strict(arr[0]),
      plaintext: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  GroupEncryptResult dco_decode_group_encrypt_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GroupEncryptResult(
      updatedRecord: dco_decode_list_prim_u_8_strict(arr[0]),
      ciphertext: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  GroupSkdmOut dco_decode_group_skdm_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GroupSkdmOut(
      updatedRecord: dco_decode_list_prim_u_8_strict(arr[0]),
      skdm: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IdentityKeypair dco_decode_identity_keypair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityKeypair(
      serialized: dco_decode_list_prim_u_8_strict(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  KyberPreKey dco_decode_kyber_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return KyberPreKey(
      id: dco_decode_u_32(arr[0]),
      serialized: dco_decode_list_prim_u_8_strict(arr[1]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[2]),
      signature: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  List<KyberPreKey> dco_decode_list_kyber_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_kyber_pre_key).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<OneTimePreKey> dco_decode_list_one_time_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_one_time_pre_key).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OneTimePreKey dco_decode_one_time_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OneTimePreKey(
      id: dco_decode_u_32(arr[0]),
      serialized: dco_decode_list_prim_u_8_strict(arr[1]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  SignedPreKey dco_decode_signed_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SignedPreKey(
      id: dco_decode_u_32(arr[0]),
      serialized: dco_decode_list_prim_u_8_strict(arr[1]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[2]),
      signature: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  DecryptResult sse_decode_decrypt_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_updatedSessionSerialized =
        sse_decode_list_prim_u_8_strict(deserializer);
    var var_plaintext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_consumedOneTimePrekeyId =
        sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_consumedKyberPrekeyId =
        sse_decode_opt_box_autoadd_u_32(deserializer);
    return DecryptResult(
        updatedSessionSerialized: var_updatedSessionSerialized,
        plaintext: var_plaintext,
        consumedOneTimePrekeyId: var_consumedOneTimePrekeyId,
        consumedKyberPrekeyId: var_consumedKyberPrekeyId);
  }

  @protected
  EncryptResult sse_decode_encrypt_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_updatedSessionSerialized =
        sse_decode_list_prim_u_8_strict(deserializer);
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_messageType = sse_decode_i_32(deserializer);
    return EncryptResult(
        updatedSessionSerialized: var_updatedSessionSerialized,
        ciphertext: var_ciphertext,
        messageType: var_messageType);
  }

  @protected
  GroupDecryptResult sse_decode_group_decrypt_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_updatedRecord = sse_decode_list_prim_u_8_strict(deserializer);
    var var_plaintext = sse_decode_list_prim_u_8_strict(deserializer);
    return GroupDecryptResult(
        updatedRecord: var_updatedRecord, plaintext: var_plaintext);
  }

  @protected
  GroupEncryptResult sse_decode_group_encrypt_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_updatedRecord = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    return GroupEncryptResult(
        updatedRecord: var_updatedRecord, ciphertext: var_ciphertext);
  }

  @protected
  GroupSkdmOut sse_decode_group_skdm_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_updatedRecord = sse_decode_list_prim_u_8_strict(deserializer);
    var var_skdm = sse_decode_list_prim_u_8_strict(deserializer);
    return GroupSkdmOut(updatedRecord: var_updatedRecord, skdm: var_skdm);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IdentityKeypair sse_decode_identity_keypair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serialized = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return IdentityKeypair(
        serialized: var_serialized, publicKey: var_publicKey);
  }

  @protected
  KyberPreKey sse_decode_kyber_pre_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_serialized = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signature = sse_decode_list_prim_u_8_strict(deserializer);
    return KyberPreKey(
        id: var_id,
        serialized: var_serialized,
        publicKey: var_publicKey,
        signature: var_signature);
  }

  @protected
  List<KyberPreKey> sse_decode_list_kyber_pre_key(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KyberPreKey>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_kyber_pre_key(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<OneTimePreKey> sse_decode_list_one_time_pre_key(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OneTimePreKey>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_one_time_pre_key(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OneTimePreKey sse_decode_one_time_pre_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_serialized = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return OneTimePreKey(
        id: var_id, serialized: var_serialized, publicKey: var_publicKey);
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SignedPreKey sse_decode_signed_pre_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_serialized = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signature = sse_decode_list_prim_u_8_strict(deserializer);
    return SignedPreKey(
        id: var_id,
        serialized: var_serialized,
        publicKey: var_publicKey,
        signature: var_signature);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_decrypt_result(DecryptResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.updatedSessionSerialized, serializer);
    sse_encode_list_prim_u_8_strict(self.plaintext, serializer);
    sse_encode_opt_box_autoadd_u_32(self.consumedOneTimePrekeyId, serializer);
    sse_encode_opt_box_autoadd_u_32(self.consumedKyberPrekeyId, serializer);
  }

  @protected
  void sse_encode_encrypt_result(EncryptResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.updatedSessionSerialized, serializer);
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
    sse_encode_i_32(self.messageType, serializer);
  }

  @protected
  void sse_encode_group_decrypt_result(
      GroupDecryptResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.updatedRecord, serializer);
    sse_encode_list_prim_u_8_strict(self.plaintext, serializer);
  }

  @protected
  void sse_encode_group_encrypt_result(
      GroupEncryptResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.updatedRecord, serializer);
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
  }

  @protected
  void sse_encode_group_skdm_out(GroupSkdmOut self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.updatedRecord, serializer);
    sse_encode_list_prim_u_8_strict(self.skdm, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_identity_keypair(
      IdentityKeypair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.serialized, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_kyber_pre_key(KyberPreKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_list_prim_u_8_strict(self.serialized, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.signature, serializer);
  }

  @protected
  void sse_encode_list_kyber_pre_key(
      List<KyberPreKey> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_kyber_pre_key(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_one_time_pre_key(
      List<OneTimePreKey> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_one_time_pre_key(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_one_time_pre_key(
      OneTimePreKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_list_prim_u_8_strict(self.serialized, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_signed_pre_key(SignedPreKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_list_prim_u_8_strict(self.serialized, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.signature, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
