// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/attachments.dart';
import 'api/identity.dart';
import 'api/prekeys.dart';
import 'api/session_1to1.dart';
import 'api/session_group.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DecryptResult dco_decode_decrypt_result(dynamic raw);

  @protected
  EncryptResult dco_decode_encrypt_result(dynamic raw);

  @protected
  GroupDecryptResult dco_decode_group_decrypt_result(dynamic raw);

  @protected
  GroupEncryptResult dco_decode_group_encrypt_result(dynamic raw);

  @protected
  GroupSkdmOut dco_decode_group_skdm_out(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IdentityKeypair dco_decode_identity_keypair(dynamic raw);

  @protected
  KyberPreKey dco_decode_kyber_pre_key(dynamic raw);

  @protected
  List<KyberPreKey> dco_decode_list_kyber_pre_key(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<OneTimePreKey> dco_decode_list_one_time_pre_key(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  OneTimePreKey dco_decode_one_time_pre_key(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  SignedPreKey dco_decode_signed_pre_key(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DecryptResult sse_decode_decrypt_result(SseDeserializer deserializer);

  @protected
  EncryptResult sse_decode_encrypt_result(SseDeserializer deserializer);

  @protected
  GroupDecryptResult sse_decode_group_decrypt_result(
      SseDeserializer deserializer);

  @protected
  GroupEncryptResult sse_decode_group_encrypt_result(
      SseDeserializer deserializer);

  @protected
  GroupSkdmOut sse_decode_group_skdm_out(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IdentityKeypair sse_decode_identity_keypair(SseDeserializer deserializer);

  @protected
  KyberPreKey sse_decode_kyber_pre_key(SseDeserializer deserializer);

  @protected
  List<KyberPreKey> sse_decode_list_kyber_pre_key(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<OneTimePreKey> sse_decode_list_one_time_pre_key(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OneTimePreKey sse_decode_one_time_pre_key(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  SignedPreKey sse_decode_signed_pre_key(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_decrypt_result(DecryptResult self, SseSerializer serializer);

  @protected
  void sse_encode_encrypt_result(EncryptResult self, SseSerializer serializer);

  @protected
  void sse_encode_group_decrypt_result(
      GroupDecryptResult self, SseSerializer serializer);

  @protected
  void sse_encode_group_encrypt_result(
      GroupEncryptResult self, SseSerializer serializer);

  @protected
  void sse_encode_group_skdm_out(GroupSkdmOut self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_identity_keypair(
      IdentityKeypair self, SseSerializer serializer);

  @protected
  void sse_encode_kyber_pre_key(KyberPreKey self, SseSerializer serializer);

  @protected
  void sse_encode_list_kyber_pre_key(
      List<KyberPreKey> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_one_time_pre_key(
      List<OneTimePreKey> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_one_time_pre_key(
      OneTimePreKey self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_signed_pre_key(SignedPreKey self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
